# Generated by Django 5.2.4 on 2025-07-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('bedrooms', models.IntegerField(verbose_name='Количество спален')),
                ('bathrooms', models.IntegerField(verbose_name='Количество ванных комнат')),
                ('area', models.IntegerField(verbose_name='Площадь (м²)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
            },
        ),
    ]
