# Generated by Django 5.2.4 on 2025-08-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('studio', 'Студия'), ('1_room', '1-комнатная'), ('2_room', '2-комнатная'), ('3_room', '3-комнатная'), ('4_room', '4-комнатная'), ('5_plus', '5+ комнат')], default='1_room', max_length=10, verbose_name='Тип недвижимости'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество спален'),
        ),
    ]
