# Generated by Django 5.2.4 on 2025-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_property_type_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=40, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
