# Generated by Django 5.2.4 on 2025-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
